name: deploy
on: [push]

jobs:
    build:
        name: Hexo Generation
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: git submodule update --init --recursive
            - name: Install Latest Pandoc
              run: |
                wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
                sudo dpkg -i ./pandoc-2.9.2.1-1-amd64.deb
            - run: yarn --frozen-lockfile
            - name: Hexo Generation
              run: yarn build
              id: hexog
            # - name: List static files
            #   run: ls -R public
            - name: Zip Files
              run: zip --junk-paths public readme.md
            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                  Changes in this Release
                  - First Change
                  - Second Change
                draft: true
                prerelease: false
            - name: Upload Release Assets
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
                asset_path: ./public.zip
                asset_name: public.zip
                asset_content_type: application/zip
            - name: Copy SSH keys
              run: |
                mkdir ~/.ssh
                echo "${{ secrets.SCP_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
            - name: Clean remote public
              run: ssh -o StrictHostKeyChecking=no root@laizn.com "rm -rf /www/public"
            - run: scp -o StrictHostKeyChecking=no -r ./public/ root@laizn.com:/www/
            - name: Clean SSH keys
              run: rm -rf ~/.ssh